# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HouseOfDesi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HouseOfDesi

  #pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'HouseOfDesiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HouseOfDesi-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HouseOfDesi-tvOS

  target 'HouseOfDesi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end




end
