# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HouseOfDesi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HouseOfDesi

  #pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit', '4.38.1'
  pod 'FBSDKLoginKit', '4.38.1'
  pod 'FBSDKShareKit', '4.38.1'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  #pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'HouseOfDesiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HouseOfDesi-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HouseOfDesi-tvOS

  target 'HouseOfDesi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end




end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
    
  end
end