export const ADD_LOCATION = "ADD LOCATION";
export const ADD_USER_DATA = "USER DATA";
export const ADD_TO_CART = "ADD TO CART";
export const DELETE_FROM_CART  = "DELETE FROM CART";
export const CART_COUNT = "UPDATE_CART_COUNT";
export const ADD_USER_ADDRESS = "USER_ADDRESS";
export const ERROR = "ON_ERROR";
export const IS_LOADING  = "IS_LOADING";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_CART_PRODUCTS = "GET_CART_PRODUCTS";
export const ADD_SCHEDULER = "ADD_SCHEDULER";
export const CANCEL_SCHEDULER = "CANCEL_SCHEDULER";
export const REMOVE_SUBSCRIBED_FROM_CART ="REMOVE_SUBSCRIBED_FROM_CART";

export const HOME_SCREEN = "HOME_SCREEN";
export const CATEGORY_PRODUCTS = "CATEGORY_PRODUCTS";
export const UPDATE_GET_ALL_PRODUCTS_QUANTITY = "UPDATE_GET_ALL_PRODUCTS_QUANTITY";
export const REMOVE_GET_ONCE_GET_ALL_PRODUCTS_QUANTITY = "REMOVE_GET_ONCE_GET_ALL_PRODUCTS_QUANTITY";
