export const ADD_LOCATION = "ADD LOCATION";
export const ADD_USER_DATA = "USER DATA";
export const ADD_TO_CART = "ADD TO CART";
export const DELETE_FROM_CART  = "DELETE FROM CART";
export const CART_COUNT = "UPDATE_CART_COUNT";
export const ADD_USER_ADDRESS = "USER_ADDRESS";
export const ERROR = "ON_ERROR";
export const IS_LOADING  = "IS_LOADING";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_CART_PRODUCTS = "GET_CART_PRODUCTS";
export const ADD_SCHEDULER = "ADD_SCHEDULER";
export const CANCEL_SCHEDULER = "CANCEL_SCHEDULER";
export const REMOVE_SUBSCRIBED_FROM_CART ="REMOVE_SUBSCRIBED_FROM_CART";

export const HOME_SCREEN = "HOME_SCREEN";
export const CATEGORY_PRODUCTS = "CATEGORY_PRODUCTS";
export const UPDATE_GET_ALL_PRODUCTS_QUANTITY = "UPDATE_GET_ALL_PRODUCTS_QUANTITY";
export const REMOVE_GET_ONCE_GET_ALL_PRODUCTS_QUANTITY = "REMOVE_GET_ONCE_GET_ALL_PRODUCTS_QUANTITY";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const GET_CART_API ="GET_CART_API";
export const USER_ID = "USER_ID";
export const CHANGE_MOBILE ="CHANGE_MOBILE";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
export const ALL_ADDRESSES = "ALL_ADDRESSES";
export const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS";

export const REMOVE_ITEM_AFTER_PAYMENT_IN_CART = "REMOVE_ITEM_AFTER_PAYMENT_IN_CART";
export const REMOVE_ITEM_AFTER_PAYMENT_IN_HOME = "REMOVE_ITEM_AFTER_PAYMENT_IN_HOME";

export const ADD_TO_CART_GETONCE_PRODUCTS_HOME = "ADD_TO_CART_GETONCE_PRODUCTS_HOME";
export const REMOVE_FROM_CART_GETONCE_PRODUCTS_HOME = "REMOVE_FROM_CART_PRODUCTS_HOME";
 
export const ADD_TO_CART_SUBSCRIBED_PRODUCTS_HOME ="ADD_TO_CART_SUBSCRIBED_PRODUCTS_HOME";
export const REMOVE_FROM_CART_SUBSCRIBED_PRODUCTS_HOME = "REMOVE_FROM_CART_SUBSCRIBED_PRODUCTS_HOME";

export const DELETE_SEARCH = "DELETE_SEARCH";